name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Setup NPM
        uses: bahmutov/npm-install@v1

      - name: Run ESLint
        run: pnpm eslint src

      - name: Build & Compile
        run: pnpm build --verbose
